"""initial schema: 13 core tables

Revision ID: 205ada30ca5f
Revises: 
Create Date: 2026-08-14 20:02:52.348999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.core.types

# revision identifiers, used by Alembic.
revision: str = '205ada30ca5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('department_id', app.core.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('membership_plans',
    sa.Column('plan_id', app.core.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'SILVER', 'GOLD', 'PLATINUM', name='membership_tier'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('consultation_discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('lab_discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pharmacy_discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('users',
    sa.Column('user_id', app.core.types.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'DOCTOR', 'RECEPTIONIST', 'NURSE', 'PHARMACIST', 'PATIENT', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', app.core.types.GUID(), nullable=False),
    sa.Column('performed_by', app.core.types.GUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_affected', sa.String(length=100), nullable=False),
    sa.Column('entity_id', app.core.types.GUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('doctors',
    sa.Column('doctor_id', app.core.types.GUID(), nullable=False),
    sa.Column('user_id', app.core.types.GUID(), nullable=False),
    sa.Column('department_id', app.core.types.GUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('qualification', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('availability_schedule', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_table('patients',
    sa.Column('patient_id', app.core.types.GUID(), nullable=False),
    sa.Column('user_id', app.core.types.GUID(), nullable=True),
    sa.Column('primary_account_id', app.core.types.GUID(), nullable=True),
    sa.Column('relationship_to_primary', sa.String(length=50), nullable=False),
    sa.Column('patient_display_id', sa.String(length=50), nullable=False),
    sa.Column('abha_id', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender_type'), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=False),
    sa.Column('known_allergies', sa.Text(), nullable=False),
    sa.Column('existing_conditions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_account_id'], ['patients.patient_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('patient_display_id')
    )
    op.create_table('appointments',
    sa.Column('appointment_id', app.core.types.GUID(), nullable=False),
    sa.Column('patient_id', app.core.types.GUID(), nullable=False),
    sa.Column('doctor_id', app.core.types.GUID(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.String(length=20), nullable=False),
    sa.Column('token_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CHECKED_IN', 'IN_CONSULTATION', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointment_status'), nullable=False),
    sa.Column('reason_for_visit', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('qr_cards',
    sa.Column('card_id', app.core.types.GUID(), nullable=False),
    sa.Column('patient_id', app.core.types.GUID(), nullable=False),
    sa.Column('token_uuid', app.core.types.GUID(), nullable=False),
    sa.Column('plan_id', app.core.types.GUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'EXPIRED', 'LOST', name='card_status'), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.plan_id'], ),
    sa.PrimaryKeyConstraint('card_id'),
    sa.UniqueConstraint('token_uuid')
    )
    op.create_table('visits',
    sa.Column('visit_id', app.core.types.GUID(), nullable=False),
    sa.Column('appointment_id', app.core.types.GUID(), nullable=True),
    sa.Column('patient_id', app.core.types.GUID(), nullable=False),
    sa.Column('doctor_id', app.core.types.GUID(), nullable=False),
    sa.Column('visit_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('symptoms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('vitals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.appointment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('visit_id')
    )
    op.create_table('invoices',
    sa.Column('invoice_id', app.core.types.GUID(), nullable=False),
    sa.Column('patient_id', app.core.types.GUID(), nullable=False),
    sa.Column('visit_id', app.core.types.GUID(), nullable=True),
    sa.Column('card_id', app.core.types.GUID(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PARTIALLY_PAID', 'PAID', 'REFUNDED', name='invoice_status'), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['qr_cards.card_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.visit_id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_table('prescriptions',
    sa.Column('prescription_id', app.core.types.GUID(), nullable=False),
    sa.Column('visit_id', app.core.types.GUID(), nullable=False),
    sa.Column('patient_id', app.core.types.GUID(), nullable=False),
    sa.Column('doctor_id', app.core.types.GUID(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.visit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prescription_id')
    )
    op.create_table('invoice_items',
    sa.Column('invoice_item_id', app.core.types.GUID(), nullable=False),
    sa.Column('invoice_id', app.core.types.GUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_item_id')
    )
    op.create_table('prescription_items',
    sa.Column('item_id', app.core.types.GUID(), nullable=False),
    sa.Column('prescription_id', app.core.types.GUID(), nullable=False),
    sa.Column('medicine_name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('intake_instructions', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.prescription_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescription_items')
    op.drop_table('invoice_items')
    op.drop_table('prescriptions')
    op.drop_table('invoices')
    op.drop_table('visits')
    op.drop_table('qr_cards')
    op.drop_table('appointments')
    op.drop_table('patients')
    op.drop_table('doctors')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('membership_plans')
    op.drop_table('departments')
    # ### end Alembic commands ###
